blank_issues_enabled: true
contact_links:
  - name: Itecoin Core Security Policy
    url: https://github.com/Itecoin/Itecoin/blob/master/SECURITY.md
    about: View security policy
  - name: Itecoin Core Developers
    url: https://Itecoincore.org
    about: Itecoin Core homepage
